


spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    cache: false
    content-type: text/html





