


spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/thymeleaf/
    cache: false
    #  freemarker:
    #    suffix: .ftl
    #    prefix: classpath:/templates/freemarker/
    #    cache: false
    #    content-type: text/html





