
spring:
  messages:
    encoding: GBK
  application:
    name: spring-boot-sample
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zsj12345
  profiles:
    active: data



