
spring:
  application:
    name: spring-boot-jpa

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zsj12345

  jpa:
    generateDdl: true
    showSql: true

server:
  prot: 8080



