package com.lesson.source.mybatis.spring;
import org.apache.ibatis.annotations.Param;
import java.io.Serializable;
import java.util.List;

/**
 * @author zhengshijun
 * @version created on 2019/1/22.
 */
public interface BaseMapper <T, E, PK extends Serializable>{


	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	long countByExample(E example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int deleteByExample(E example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int deleteByPrimaryKey(PK id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int insert(T record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int insertSelective(T record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	List<T> selectByExample(E example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	T selectByPrimaryKey(PK id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int updateByExample(@Param("record") T record, @Param("example") E example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int updateByPrimaryKeySelective(T record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table t_user_bank_info
	 *
	 * @mbg.generated 2019-01-22 19:51:47
	 */
	int updateByPrimaryKey(T record);
}
