spring:
  application:
    name: spring-cloud-gateway-sample
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: 123456
        uri: lb://spring-cloud-zookeeper-provider
        predicates:
        - Path=/invoker/**
logging:
  level:
    root: INFO
server:
  port: 7071


