

spring:
  application:
    name : spring-cloud-stream-rabbit-sample

  cloud:
    stream:
      bindings:
        channel_name_arg0:
          destination: sample-demo1
          content-type: application/json
        channel_name_arg1:
          destination: sample-demo1
          content-type: application/json
          group: ${spring.application.name}
#        channel_name_arg2:
#          destination: sample-demo1
#          content-type: application/json
#          group: hello-1

  rabbitmq:
    host: 121.196.232.248



server:
  port: 0


